
GET http://localhost:3000

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/64ed4b9b3ad737bd78b5da5f

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "route test 1",
    "source_id": "ChIJAQULSLD2k5QR3C6OdqmEoXE",
    "destination_id": "ChIJ1TpgPyD0k5QRimbaavaKeJo"
}

### Coisas do mapa

### Pegar o place_id
GET http://localhost:3000/places?text=R. wilson calza, presidente prudente, 183

### Minha casa
### ChIJAQULSLD2k5QR3C6OdqmEoXE

### Casa da Bi
### ChIJ1TpgPyD0k5QRimbaavaKeJo

### Pegar direções entre 2 pontos
GET http://localhost:3000/directions?originId=ChIJAQULSLD2k5QR3C6OdqmEoXE&destinationId=ChIJ1TpgPyD0k5QRimbaavaKeJo
